import { ICharacterData } from '../interfaces/ICharacterData.interface';

export const CharacterData: ICharacterData[] = [
    {
        Name: 'Diluc',
        img: 'diluc',
        Title: 'The Dark Side of Dawn',
        Allegiance: 'Dawn Winery',
        WeaponType: 'Claymore',
        Birthday: '30 April',
        Element: 'Pyro',
        Constellation: 'Noctua',
        Rarity: 5
    },
    {
        Name: 'Jean',
        img: 'jean',
        Title: 'Dandelion Knight',
        Allegiance: 'Knights of Favonius',
        WeaponType: 'Sword',
        Birthday: '14 March',
        Element: 'Anemo',
        Constellation: 'Leo Minor',
        Rarity: 5
    },
    {
        Name: 'Keqing',
        img: 'keqing',
        Title: 'Driving Thunder',
        Allegiance: 'Liyue Qixing',
        WeaponType: 'Sword',
        Birthday: '20 November',
        Element: 'Electro',
        Constellation: 'Trulla Cementarii',
        Rarity: 5
    },
    {
        Name: 'Klee',
        img: 'klee',
        Title: 'Fleeing Sunlight',
        Allegiance: 'Knights of Favonius',
        WeaponType: 'Catalyst',
        Birthday: '27 July',
        Element: 'Pyro',
        Constellation: 'Trifolium',
        Rarity: 5
    },
    {
        Name: 'Mona',
        img: 'mona',
        Title: 'Astral Reflection',
        Allegiance: 'Mondstadt',
        WeaponType: 'Catalyst',
        Birthday: '31 August',
        Element: 'Hydro',
        Constellation: 'Astrolabos',
        Rarity: 5
    },
    {
        Name: 'Qiqi',
        img: 'qiqi',
        Title: 'Icy Resurrection',
        Allegiance: 'Bubu Pharmacy',
        WeaponType: 'Sword',
        Birthday: '3 March',
        Element: 'Cryo',
        Constellation: 'Pristina Nola',
        Rarity: 5
    },
    {
        Name: 'Venti',
        img: 'venti',
        Title: 'Windbprne Bard',
        Allegiance: 'Mondstadt',
        WeaponType: 'Bow',
        Birthday: '16 June',
        Element: 'Anemo',
        Constellation: 'Erika Harlacher',
        Rarity: 5
    },
    {
        Name: 'Xiao',
        img: 'xiao',
        Title: 'Vigilant Yaksha',
        Allegiance: 'Liyue Adeptus',
        WeaponType: 'Polearm',
        Birthday: '17 April',
        Element: 'Anemo',
        Constellation: 'Alatus Nemeseos',
        Rarity: 5
    },
    {
        Name: 'Tartaglia',
        img: 'tartaglia',
        Title: 'Childe',
        Allegiance: 'Fatui',
        WeaponType: 'Bow',
        Birthday: '20 July',
        Element: 'Hydro',
        Constellation: 'Monoceros Caeli',
        Rarity: 5
    },
    {
        Name: 'Zhongli',
        img: 'zhongli',
        Title: 'Vago Mundo',
        Allegiance: 'Liyue Harbor',
        WeaponType: 'Polearm',
        Birthday: '31 December',
        Element: 'Geo',
        Constellation: 'Lapis Dei',
        Rarity: 5
    },
    {
        Name: 'Ganyu',
        img: 'ganyu',
        Title: 'Plenilune Gaze',
        Allegiance: 'Yuehai Pavilion',
        WeaponType: 'Bow',
        Birthday: '2 December',
        Element: 'Cryo',
        Constellation: 'Sinae Unicornis',
        Rarity: 5
    },
    {
        Name: 'Albedo',
        img: 'albedo',
        Title: 'Kreideprinz',
        Allegiance: 'Yuehai Pavilion',
        WeaponType: 'Sword',
        Birthday: '13 September',
        Element: 'Geo',
        Constellation: 'Princeps Cretaceus',
        Rarity: 5
    },
    {
        Name: 'Hu Tao',
        img: 'hutao',
        Title: 'Fragrance in Thaw',
        Allegiance: 'Wangsheng Funeral Parlor',
        WeaponType: 'Polearm',
        Birthday: '15 July',
        Element: 'Pyro',
        Constellation: 'Papilio Charontis',
        Rarity: 5
    },
    {
        Name: 'Amber',
        img: 'amber',
        Title: 'Gliding Champion',
        Allegiance: 'Knights of Favonius',
        WeaponType: 'Bow',
        Birthday: '10 August',
        Element: 'Pyro',
        Constellation: 'Lepus',
        Rarity: 4
    },
    {
        Name: 'Barbara',
        img: 'barbara',
        Title: 'Shining Idol',
        Allegiance: 'Church of Favonius',
        WeaponType: 'Catalyst',
        Birthday: '5 July',
        Element: 'Hydro',
        Constellation: 'Crater',
        Rarity: 4
    },
    {
        Name: 'Beidou',
        img: 'beidou',
        Title: 'Uncrowned Lord of the Ocean',
        Allegiance: 'The Crux',
        WeaponType: 'Claymore',
        Birthday: '14 February',
        Element: 'Electro',
        Constellation: 'Victor Mare',
        Rarity: 4
    },
    {
        Name: 'Bennett',
        img: 'bennett',
        Title: 'Trial by Fire',
        Allegiance: 'Adventurers\' Guild',
        WeaponType: 'Sword',
        Birthday: '29 February',
        Element: 'Pyro',
        Constellation: 'Rota Calamitas',
        Rarity: 4
    },
    {
        Name: 'Chongyun',
        img: 'chongyun',
        Title: 'Frozen Ardor',
        Allegiance: 'Liyue Harbor',
        WeaponType: 'Claymore',
        Birthday: '7 September',
        Element: 'Cryo',
        Constellation: 'Nubis Caesor',
        Rarity: 4
    },
    {
        Name: 'Fischl',
        img: 'fischl',
        Title: 'Prinzessin der Verurteilung!',
        Allegiance: 'Adventurers\' Guild',
        WeaponType: 'Bow',
        Birthday: '27 May',
        Element: 'Electro',
        Constellation: 'Corvus',
        Rarity: 4
    },
    {
        Name: 'Kaeya',
        img: 'kaeya',
        Title: 'Frostwind Swordsman',
        Allegiance: 'Knights of Favonius',
        WeaponType: 'Sword',
        Birthday: '30 November',
        Element: 'Cryo',
        Constellation: 'Pavo Ocellus',
        Rarity: 4
    },
    {
        Name: 'Lisa',
        img: 'lisa',
        Title: 'Witch of Purple Rose',
        Allegiance: 'Knights of Favonius',
        WeaponType: 'Catalyst',
        Birthday: '9 June',
        Element: 'Electro',
        Constellation: 'Tempus Fugit',
        Rarity: 4
    },
    {
        Name: 'Ningguang',
        img: 'ningguang',
        Title: 'Eclipsing Star',
        Allegiance: 'Liyue Qixing',
        WeaponType: 'Catalyst',
        Birthday: '26 August',
        Element: 'Geo',
        Constellation: 'Opus Aequilibrium',
        Rarity: 4
    },
    {
        Name: 'Noelle',
        img: 'noelle',
        Title: 'Chivalric Blossom',
        Allegiance: 'Knights of Favonius',
        WeaponType: 'Claymore',
        Birthday: '21 March',
        Element: 'Geo',
        Constellation: 'Parma Cordis',
        Rarity: 4
    },
    {
        Name: 'Razor',
        img: 'razor',
        Title: 'Wolf Boy',
        Allegiance: 'Wolvendom',
        WeaponType: 'Claymore',
        Birthday: '9 September',
        Element: 'Electro',
        Constellation: 'Lupus Minor',
        Rarity: 4
    },
    {
        Name: 'Sucrose',
        img: 'sucrose',
        Title: 'Harmless Sweetie',
        Allegiance: 'Knights of Favonius',
        WeaponType: 'Catalyst',
        Birthday: '26 November',
        Element: 'Anemo',
        Constellation: 'Ampulla',
        Rarity: 4
    },
    {
        Name: 'Xiangling',
        img: 'xiangling',
        Title: 'Exquisite Delicacy',
        Allegiance: 'Wanmin Restaurant',
        WeaponType: 'Polearm',
        Birthday: '2 November',
        Element: 'Pyro',
        Constellation: 'Trulla',
        Rarity: 4
    },
    {
        Name: 'Xingqiu',
        img: 'xingqiu',
        Title: 'Juvenile Galant',
        Allegiance: 'Feiyun Commerce Guild',
        WeaponType: 'Sword',
        Birthday: '9 October',
        Element: 'Hydro',
        Constellation: 'Fabulae Textile',
        Rarity: 4
    },
    {
        Name: 'Diona',
        img: 'diona',
        Title: 'Kätzlein Cocktail',
        Allegiance: 'The Cat\'s Tail',
        WeaponType: 'Bow',
        Birthday: '18 January',
        Element: 'Cryo',
        Constellation: 'Feles',
        Rarity: 4
    },
    {
        Name: 'Xinyan',
        img: 'xinyan',
        Title: 'Blazing Riff',
        Allegiance: 'Liyue Harbor',
        WeaponType: 'Claymore',
        Birthday: '16 October',
        Element: 'Pyro',
        Constellation: 'Fila Ignium',
        Rarity: 4
    },
    {
        Name: 'Rosaria',
        img: 'rosaria',
        Title: 'Thorny Benevolence',
        Allegiance: 'Church of Favonius',
        WeaponType: 'Polearm',
        Birthday: '24 January',
        Element: 'Cryo',
        Constellation: 'Spinea Corona',
        Rarity: 4
    },
    {
        Name: 'Yanfei',
        img: 'yanfei',
        Title: 'Wise Innocence',
        Allegiance: 'Liyue Harbor',
        WeaponType: 'Catalyst',
        Birthday: '28 July',
        Element: 'Pyro',
        Constellation: 'Bestia Iustitia',
        Rarity: 4
    }
];
